[workspace]
members = [
    "cli",
    "clients/rust/jito_tip_router",
    "core",
    "integration_tests",
    "program",
    "shank_cli",
    "tip-router-operator-cli",
    "tip_distribution_sdk", "tip_payment_sdk",
]

resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.package]
version = "0.0.1"
authors = ["Jito Network Maintainers <support@jito.network>"]
repository = "https://github.com/jito-foundation/restaking"
homepage = "https://jito.network/"
license = "Apache License 2.0"
edition = "2021"
readme = "README.md"

[workspace.dependencies]
anchor-lang = { git = "https://github.com/coral-xyz/anchor", rev = "96ed3b791c6fed9ab64cb138397795fe55991280" }
anyhow = "1.0.86"
assert_matches = "1.5.0"
borsh = { version = "0.10.3" }
bytemuck = { version = "1.16.3", features = ["min_const_generics"] }
cfg-if = "1.0.0"
chrono = "0.4.38"
clap = { version = "4.5.16", features = ["derive", "env", "cargo"] }
clap_old = { package = "clap", version = "2.33.1" }
clap-markdown = { version = "0.1.4" }
const_str_to_pubkey = "0.2.0"
dotenv = "0.15.0"
envfile = "0.2.1"
env_logger = "0.10.2"
fast-math = "0.1"
futures = "0.3.21"
getrandom = { version = "0.1.16", features = ["custom"] }
hex = "0.4.3"
home = "=0.5.9" # Custom for compatibility with rust 1.75
log = "0.4.22"
matches = "0.1.10"
num-derive = "0.4.2"
num-traits = "0.2.19"
proc-macro2 = "1.0.86"
quote = "1.0.36"
rand = "0.8.5"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.102"
serde_with = "3.9.0"
serde-big-array = "0.5.1"
shank = "0.4.2"
shank_idl = "0.4.2"
spl-math = { version = "0.3.0", features = ["no-entrypoint"] }
spl-memo = "6.0.0"
solana-account-decoder = { version = "=2.1.11" }
solana-metrics = { version = "=2.1.11" }
solana-accounts-db = { version = "=2.1.11" }
solana-clap-utils = { version = "=2.1.11" }
solana-client = { version = "=2.1.11" }
solana-core = { version = "=2.1.11" }
solana-geyser-plugin-manager = { version = "=2.1.11" }
solana-gossip = { version = "=2.1.11" }
solana-measure = { version = "=2.1.11" }
solana-ledger = { version = "=2.1.11" }
solana-program = { version = "=2.1.11" }
solana-transaction-status = { version = "=2.1.11" }
solana-program-test = { version = "=2.1.11" }
solana-rpc-client = { version = "=2.1.11" }
solana-rpc = { version = "=2.1.11" }
solana-rpc-client-api = { version = "=2.1.11" }
solana-runtime = { version = "=2.1.11" }
solana-streamer = { version = "=2.1.11" }
solana-sdk = { version = "=2.1.11" }
solana-stake-program = { version = "=2.1.11" }
solana-vote = { version = "=2.1.11" }
solana-unified-scheduler-pool = { version = "=2.1.11" }
solana-zk-sdk = { version = "=2.1.11" }
solana-zk-token-sdk = { version = "=2.1.11" }
solana-instruction = { version = "=2.1.11" }
solana-program-error = { version = "=2.1.11" }
solana-pubkey = { version = "=2.1.11" }
solana-account-info = { version = "=2.1.11" }
solana-program-entrypoint = { version = "=2.1.11" }
solana-decode-error = { version = "=2.1.11" }
solana-security-txt = "1.1.1"
spl-associated-token-account = { version = "6.0.0", features = ["no-entrypoint"] }
spl-stake-pool = { version = "2.0.1", features = ["no-entrypoint"] }
spl-token = { version = "7.0.0", features = ["no-entrypoint"] }
spl-token-2022 = { version = "=7.0.0", features = ["no-entrypoint"] }
switchboard-on-demand = "0.3.4"
syn = "2.0.72"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
meta-merkle-tree = { path = "./meta_merkle_tree", version = "=0.0.1" }
jito-tip-distribution-sdk = { path = "./tip_distribution_sdk", version = "=0.0.1" }
jito-tip-payment-sdk = { path = "./tip_payment_sdk", version = "=0.0.1" }
jito-tip-router-client = { path = "./clients/rust/jito_tip_router", version = "0.0.1" }
jito-tip-router-core = { path = "./core", version = "=0.0.1" }
jito-tip-router-program = { path = "./program", version = "=0.0.1" }
jito-tip-router-shank-cli = { path = "./shank_cli", version = "=0.0.1" }
jito-bytemuck = { package = "jito-bytemuck", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade" }
jito-account-traits-derive = { package = "jito-account-traits-derive", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade" }
jito-jsm-core = { package = "jito-jsm-core", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade" }
jito-restaking-client = { package = "jito-restaking-client", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade" }
jito-restaking-core = { package = "jito-restaking-core", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade" }
jito-restaking-program = { package = "jito-restaking-program", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade", features = ["no-entrypoint"] }
jito-restaking-sdk = { package = "jito-restaking-sdk", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade" }
jito-vault-client = { package = "jito-vault-client", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade" }
jito-vault-core = { package = "jito-vault-core", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade" }
jito-vault-program = { package = "jito-vault-program", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade", features = ["no-entrypoint"] }
jito-vault-sdk = { package = "jito-vault-sdk", git = "https://github.com/jito-foundation/restaking", branch = "v2.1-upgrade" }
