services:
  jito-tip-router-ncn-keeper:
    build:
      context: .
      dockerfile: cli/Dockerfile
    container_name: jito-tip-router-ncn-keeper
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - RPC_URL=${RPC_URL}
      - PRIORITY_FEE_MICRO_LAMPORTS=${PRIORITY_FEE_MICRO_LAMPORTS}
      - KEYPAIR_PATH=${KEYPAIR_PATH}
      - NCN=${NCN}
      - EPOCH=${EPOCH}
      - VAULT_PROGRAM_ID=${VAULT_PROGRAM_ID}
      - RESTAKING_PROGRAM_ID=${RESTAKING_PROGRAM_ID}
      - TIP_ROUTER_PROGRAM_ID=${TIP_ROUTER_PROGRAM_ID}
      - SOLANA_METRICS_CONFIG=${SOLANA_METRICS_CONFIG}
      - LOOP_TIMEOUT_MS=${LOOP_TIMEOUT_MS}
      - ERROR_TIMEOUT_MS=${ERROR_TIMEOUT_MS}
      - ALL_VAULT_UPDATE=${ALL_VAULT_UPDATE}
      - EMIT_METRICS=false
      - METRICS_ONLY=false
      - RUN_MIGRATION=false
      - TRANSACTION_RETRIES=2
    volumes:
      - ./credentials:/credentials
    restart: on-failure:5
  jito-tip-router-ncn-keeper-metrics-only:
    build:
      context: .
      dockerfile: cli/Dockerfile
    container_name: jito-tip-router-ncn-keeper-metrics-only
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - RPC_URL=${RPC_URL}
      - PRIORITY_FEE_MICRO_LAMPORTS=${PRIORITY_FEE_MICRO_LAMPORTS}
      - KEYPAIR_PATH=${KEYPAIR_PATH}
      - NCN=${NCN}
      - EPOCH=${EPOCH}
      - VAULT_PROGRAM_ID=${VAULT_PROGRAM_ID}
      - RESTAKING_PROGRAM_ID=${RESTAKING_PROGRAM_ID}
      - TIP_ROUTER_PROGRAM_ID=${TIP_ROUTER_PROGRAM_ID}
      - SOLANA_METRICS_CONFIG=${SOLANA_METRICS_CONFIG}
      - LOOP_TIMEOUT_MS=${LOOP_TIMEOUT_MS}
      - ERROR_TIMEOUT_MS=${ERROR_TIMEOUT_MS}
      - ALL_VAULT_UPDATE=${ALL_VAULT_UPDATE}
      - EMIT_METRICS=true
      - METRICS_ONLY=true
      - RUN_MIGRATION=false
    volumes:
      - ./credentials:/credentials
    restart: on-failure:5
  jito-tip-router-ncn-keeper-migrate-only:
    build:
      context: .
      dockerfile: cli/Dockerfile
    container_name: jito-tip-router-ncn-keeper-migrate-only
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - RPC_URL=${RPC_URL}
      - PRIORITY_FEE_MICRO_LAMPORTS=${PRIORITY_FEE_MICRO_LAMPORTS}
      - KEYPAIR_PATH=${KEYPAIR_PATH}
      - NCN=${NCN}
      - EPOCH=751
      - VAULT_PROGRAM_ID=${VAULT_PROGRAM_ID}
      - RESTAKING_PROGRAM_ID=${RESTAKING_PROGRAM_ID}
      - TIP_ROUTER_PROGRAM_ID=${TIP_ROUTER_PROGRAM_ID}
      - SOLANA_METRICS_CONFIG=${SOLANA_METRICS_CONFIG}
      - LOOP_TIMEOUT_MS=34000
      - ERROR_TIMEOUT_MS=${ERROR_TIMEOUT_MS}
      - ALL_VAULT_UPDATE=${ALL_VAULT_UPDATE}
      - EMIT_METRICS=false
      - METRICS_ONLY=false
      - RUN_MIGRATION=true
      - TRANSACTION_RETRIES=5
    volumes:
      - ./credentials:/credentials
    restart: on-failure:5
