/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import { getFeeDecoder, getFeeEncoder, type Fee, type FeeArgs } from '.';

export type Fees = {
  activationEpoch: bigint;
  reserved: ReadonlyUint8Array;
  baseFeeGroupsBps: Array<Fee>;
  ncnFeeGroupsBps: Array<Fee>;
};

export type FeesArgs = {
  activationEpoch: number | bigint;
  reserved: ReadonlyUint8Array;
  baseFeeGroupsBps: Array<FeeArgs>;
  ncnFeeGroupsBps: Array<FeeArgs>;
};

export function getFeesEncoder(): Encoder<FeesArgs> {
  return getStructEncoder([
    ['activationEpoch', getU64Encoder()],
    ['reserved', fixEncoderSize(getBytesEncoder(), 128)],
    ['baseFeeGroupsBps', getArrayEncoder(getFeeEncoder(), { size: 8 })],
    ['ncnFeeGroupsBps', getArrayEncoder(getFeeEncoder(), { size: 8 })],
  ]);
}

export function getFeesDecoder(): Decoder<Fees> {
  return getStructDecoder([
    ['activationEpoch', getU64Decoder()],
    ['reserved', fixDecoderSize(getBytesDecoder(), 128)],
    ['baseFeeGroupsBps', getArrayDecoder(getFeeDecoder(), { size: 8 })],
    ['ncnFeeGroupsBps', getArrayDecoder(getFeeDecoder(), { size: 8 })],
  ]);
}

export function getFeesCodec(): Codec<FeesArgs, Fees> {
  return combineCodec(getFeesEncoder(), getFeesDecoder());
}
