/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';
import {
  getNcnFeeDecoder,
  getNcnFeeEncoder,
  type NcnFee,
  type NcnFeeArgs,
} from '.';

export type Fees = {
  activationEpoch: bigint;
  blockEngineFeeBps: bigint;
  daoFeeBps: bigint;
  reserved: Array<number>;
  ncnFeeGroupsBps: Array<NcnFee>;
};

export type FeesArgs = {
  activationEpoch: number | bigint;
  blockEngineFeeBps: number | bigint;
  daoFeeBps: number | bigint;
  reserved: Array<number>;
  ncnFeeGroupsBps: Array<NcnFeeArgs>;
};

export function getFeesEncoder(): Encoder<FeesArgs> {
  return getStructEncoder([
    ['activationEpoch', getU64Encoder()],
    ['blockEngineFeeBps', getU64Encoder()],
    ['daoFeeBps', getU64Encoder()],
    ['reserved', getArrayEncoder(getU8Encoder(), { size: 128 })],
    ['ncnFeeGroupsBps', getArrayEncoder(getNcnFeeEncoder(), { size: 16 })],
  ]);
}

export function getFeesDecoder(): Decoder<Fees> {
  return getStructDecoder([
    ['activationEpoch', getU64Decoder()],
    ['blockEngineFeeBps', getU64Decoder()],
    ['daoFeeBps', getU64Decoder()],
    ['reserved', getArrayDecoder(getU8Decoder(), { size: 128 })],
    ['ncnFeeGroupsBps', getArrayDecoder(getNcnFeeDecoder(), { size: 16 })],
  ]);
}

export function getFeesCodec(): Codec<FeesArgs, Fees> {
  return combineCodec(getFeesEncoder(), getFeesDecoder());
}
