/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import {
  getNcnFeeGroupDecoder,
  getNcnFeeGroupEncoder,
  type NcnFeeGroup,
  type NcnFeeGroupArgs,
} from '.';

export type MintEntry = {
  stMint: Address;
  vaultIndex: bigint;
  ncnFeeGroup: NcnFeeGroup;
  reserved: ReadonlyUint8Array;
};

export type MintEntryArgs = {
  stMint: Address;
  vaultIndex: number | bigint;
  ncnFeeGroup: NcnFeeGroupArgs;
  reserved: ReadonlyUint8Array;
};

export function getMintEntryEncoder(): Encoder<MintEntryArgs> {
  return getStructEncoder([
    ['stMint', getAddressEncoder()],
    ['vaultIndex', getU64Encoder()],
    ['ncnFeeGroup', getNcnFeeGroupEncoder()],
    ['reserved', fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

export function getMintEntryDecoder(): Decoder<MintEntry> {
  return getStructDecoder([
    ['stMint', getAddressDecoder()],
    ['vaultIndex', getU64Decoder()],
    ['ncnFeeGroup', getNcnFeeGroupDecoder()],
    ['reserved', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getMintEntryCodec(): Codec<MintEntryArgs, MintEntry> {
  return combineCodec(getMintEntryEncoder(), getMintEntryDecoder());
}
