/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';

export type NcnFee = { fee: bigint; reserved: ReadonlyUint8Array };

export type NcnFeeArgs = { fee: number | bigint; reserved: ReadonlyUint8Array };

export function getNcnFeeEncoder(): Encoder<NcnFeeArgs> {
  return getStructEncoder([
    ['fee', getU64Encoder()],
    ['reserved', fixEncoderSize(getBytesEncoder(), 64)],
  ]);
}

export function getNcnFeeDecoder(): Decoder<NcnFee> {
  return getStructDecoder([
    ['fee', getU64Decoder()],
    ['reserved', fixDecoderSize(getBytesDecoder(), 64)],
  ]);
}

export function getNcnFeeCodec(): Codec<NcnFeeArgs, NcnFee> {
  return combineCodec(getNcnFeeEncoder(), getNcnFeeDecoder());
}
