/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type NcnFee = { fee: bigint };

export type NcnFeeArgs = { fee: number | bigint };

export function getNcnFeeEncoder(): Encoder<NcnFeeArgs> {
  return getStructEncoder([['fee', getU64Encoder()]]);
}

export function getNcnFeeDecoder(): Decoder<NcnFee> {
  return getStructDecoder([['fee', getU64Decoder()]]);
}

export function getNcnFeeCodec(): Codec<NcnFeeArgs, NcnFee> {
  return combineCodec(getNcnFeeEncoder(), getNcnFeeDecoder());
}
