/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';

export type VaultOperatorVotes = {
  vault: Address;
  votes: bigint;
  vaultIndex: bigint;
  reserved: ReadonlyUint8Array;
};

export type VaultOperatorVotesArgs = {
  vault: Address;
  votes: number | bigint;
  vaultIndex: number | bigint;
  reserved: ReadonlyUint8Array;
};

export function getVaultOperatorVotesEncoder(): Encoder<VaultOperatorVotesArgs> {
  return getStructEncoder([
    ['vault', getAddressEncoder()],
    ['votes', getU128Encoder()],
    ['vaultIndex', getU64Encoder()],
    ['reserved', fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

export function getVaultOperatorVotesDecoder(): Decoder<VaultOperatorVotes> {
  return getStructDecoder([
    ['vault', getAddressDecoder()],
    ['votes', getU128Decoder()],
    ['vaultIndex', getU64Decoder()],
    ['reserved', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getVaultOperatorVotesCodec(): Codec<
  VaultOperatorVotesArgs,
  VaultOperatorVotes
> {
  return combineCodec(
    getVaultOperatorVotesEncoder(),
    getVaultOperatorVotesDecoder()
  );
}
