/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';

export type VaultEntry = {
  vault: Address;
  stMint: Address;
  vaultIndex: bigint;
  slotRegistered: bigint;
  reserved: ReadonlyUint8Array;
};

export type VaultEntryArgs = {
  vault: Address;
  stMint: Address;
  vaultIndex: number | bigint;
  slotRegistered: number | bigint;
  reserved: ReadonlyUint8Array;
};

export function getVaultEntryEncoder(): Encoder<VaultEntryArgs> {
  return getStructEncoder([
    ['vault', getAddressEncoder()],
    ['stMint', getAddressEncoder()],
    ['vaultIndex', getU64Encoder()],
    ['slotRegistered', getU64Encoder()],
    ['reserved', fixEncoderSize(getBytesEncoder(), 128)],
  ]);
}

export function getVaultEntryDecoder(): Decoder<VaultEntry> {
  return getStructDecoder([
    ['vault', getAddressDecoder()],
    ['stMint', getAddressDecoder()],
    ['vaultIndex', getU64Decoder()],
    ['slotRegistered', getU64Decoder()],
    ['reserved', fixDecoderSize(getBytesDecoder(), 128)],
  ]);
}

export function getVaultEntryCodec(): Codec<VaultEntryArgs, VaultEntry> {
  return combineCodec(getVaultEntryEncoder(), getVaultEntryDecoder());
}
