/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import {
  getStMintEntryDecoder,
  getStMintEntryEncoder,
  type StMintEntry,
  type StMintEntryArgs,
} from '.';

export type WeightEntry = {
  stMintEntry: StMintEntry;
  weight: bigint;
  slotSet: bigint;
  slotUpdated: bigint;
  reserved: ReadonlyUint8Array;
};

export type WeightEntryArgs = {
  stMintEntry: StMintEntryArgs;
  weight: number | bigint;
  slotSet: number | bigint;
  slotUpdated: number | bigint;
  reserved: ReadonlyUint8Array;
};

export function getWeightEntryEncoder(): Encoder<WeightEntryArgs> {
  return getStructEncoder([
    ['stMintEntry', getStMintEntryEncoder()],
    ['weight', getU128Encoder()],
    ['slotSet', getU64Encoder()],
    ['slotUpdated', getU64Encoder()],
    ['reserved', fixEncoderSize(getBytesEncoder(), 128)],
  ]);
}

export function getWeightEntryDecoder(): Decoder<WeightEntry> {
  return getStructDecoder([
    ['stMintEntry', getStMintEntryDecoder()],
    ['weight', getU128Decoder()],
    ['slotSet', getU64Decoder()],
    ['slotUpdated', getU64Decoder()],
    ['reserved', fixDecoderSize(getBytesDecoder(), 128)],
  ]);
}

export function getWeightEntryCodec(): Codec<WeightEntryArgs, WeightEntry> {
  return combineCodec(getWeightEntryEncoder(), getWeightEntryDecoder());
}
