/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type TransactionSigner,
  type WritableSignerAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INITIALIZE_EPOCH_REWARD_ROUTER_DISCRIMINATOR = 10;

export function getInitializeEpochRewardRouterDiscriminatorBytes() {
  return getU8Encoder().encode(INITIALIZE_EPOCH_REWARD_ROUTER_DISCRIMINATOR);
}

export type InitializeEpochRewardRouterInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountRestakingConfig extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountBallotBox extends string | IAccountMeta<string> = string,
  TAccountEpochRewardRouter extends string | IAccountMeta<string> = string,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TAccountRestakingProgramId extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountRestakingConfig extends string
        ? ReadonlyAccount<TAccountRestakingConfig>
        : TAccountRestakingConfig,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountBallotBox extends string
        ? ReadonlyAccount<TAccountBallotBox>
        : TAccountBallotBox,
      TAccountEpochRewardRouter extends string
        ? ReadonlyAccount<TAccountEpochRewardRouter>
        : TAccountEpochRewardRouter,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            IAccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountRestakingProgramId extends string
        ? ReadonlyAccount<TAccountRestakingProgramId>
        : TAccountRestakingProgramId,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeEpochRewardRouterInstructionData = {
  discriminator: number;
  firstSlotOfNcnEpoch: Option<bigint>;
};

export type InitializeEpochRewardRouterInstructionDataArgs = {
  firstSlotOfNcnEpoch: OptionOrNullable<number | bigint>;
};

export function getInitializeEpochRewardRouterInstructionDataEncoder(): Encoder<InitializeEpochRewardRouterInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['firstSlotOfNcnEpoch', getOptionEncoder(getU64Encoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_EPOCH_REWARD_ROUTER_DISCRIMINATOR,
    })
  );
}

export function getInitializeEpochRewardRouterInstructionDataDecoder(): Decoder<InitializeEpochRewardRouterInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['firstSlotOfNcnEpoch', getOptionDecoder(getU64Decoder())],
  ]);
}

export function getInitializeEpochRewardRouterInstructionDataCodec(): Codec<
  InitializeEpochRewardRouterInstructionDataArgs,
  InitializeEpochRewardRouterInstructionData
> {
  return combineCodec(
    getInitializeEpochRewardRouterInstructionDataEncoder(),
    getInitializeEpochRewardRouterInstructionDataDecoder()
  );
}

export type InitializeEpochRewardRouterInput<
  TAccountRestakingConfig extends string = string,
  TAccountNcn extends string = string,
  TAccountBallotBox extends string = string,
  TAccountEpochRewardRouter extends string = string,
  TAccountPayer extends string = string,
  TAccountRestakingProgramId extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  restakingConfig: Address<TAccountRestakingConfig>;
  ncn: Address<TAccountNcn>;
  ballotBox: Address<TAccountBallotBox>;
  epochRewardRouter: Address<TAccountEpochRewardRouter>;
  payer: TransactionSigner<TAccountPayer>;
  restakingProgramId: Address<TAccountRestakingProgramId>;
  systemProgram?: Address<TAccountSystemProgram>;
  firstSlotOfNcnEpoch: InitializeEpochRewardRouterInstructionDataArgs['firstSlotOfNcnEpoch'];
};

export function getInitializeEpochRewardRouterInstruction<
  TAccountRestakingConfig extends string,
  TAccountNcn extends string,
  TAccountBallotBox extends string,
  TAccountEpochRewardRouter extends string,
  TAccountPayer extends string,
  TAccountRestakingProgramId extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: InitializeEpochRewardRouterInput<
    TAccountRestakingConfig,
    TAccountNcn,
    TAccountBallotBox,
    TAccountEpochRewardRouter,
    TAccountPayer,
    TAccountRestakingProgramId,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeEpochRewardRouterInstruction<
  TProgramAddress,
  TAccountRestakingConfig,
  TAccountNcn,
  TAccountBallotBox,
  TAccountEpochRewardRouter,
  TAccountPayer,
  TAccountRestakingProgramId,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    restakingConfig: {
      value: input.restakingConfig ?? null,
      isWritable: false,
    },
    ncn: { value: input.ncn ?? null, isWritable: false },
    ballotBox: { value: input.ballotBox ?? null, isWritable: false },
    epochRewardRouter: {
      value: input.epochRewardRouter ?? null,
      isWritable: false,
    },
    payer: { value: input.payer ?? null, isWritable: true },
    restakingProgramId: {
      value: input.restakingProgramId ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.restakingConfig),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.ballotBox),
      getAccountMeta(accounts.epochRewardRouter),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.restakingProgramId),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitializeEpochRewardRouterInstructionDataEncoder().encode(
      args as InitializeEpochRewardRouterInstructionDataArgs
    ),
  } as InitializeEpochRewardRouterInstruction<
    TProgramAddress,
    TAccountRestakingConfig,
    TAccountNcn,
    TAccountBallotBox,
    TAccountEpochRewardRouter,
    TAccountPayer,
    TAccountRestakingProgramId,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedInitializeEpochRewardRouterInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    restakingConfig: TAccountMetas[0];
    ncn: TAccountMetas[1];
    ballotBox: TAccountMetas[2];
    epochRewardRouter: TAccountMetas[3];
    payer: TAccountMetas[4];
    restakingProgramId: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: InitializeEpochRewardRouterInstructionData;
};

export function parseInitializeEpochRewardRouterInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedInitializeEpochRewardRouterInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      restakingConfig: getNextAccount(),
      ncn: getNextAccount(),
      ballotBox: getNextAccount(),
      epochRewardRouter: getNextAccount(),
      payer: getNextAccount(),
      restakingProgramId: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeEpochRewardRouterInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
