/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type TransactionSigner,
  type WritableSignerAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const INITIALIZE_OPERATOR_EPOCH_REWARD_ROUTER_DISCRIMINATOR = 11;

export function getInitializeOperatorEpochRewardRouterDiscriminatorBytes() {
  return getU8Encoder().encode(
    INITIALIZE_OPERATOR_EPOCH_REWARD_ROUTER_DISCRIMINATOR
  );
}

export type InitializeOperatorEpochRewardRouterInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountRestakingConfig extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountOperator extends string | IAccountMeta<string> = string,
  TAccountBallotBox extends string | IAccountMeta<string> = string,
  TAccountOperatorEpochRewardRouter extends
    | string
    | IAccountMeta<string> = string,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TAccountRestakingProgramId extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountRestakingConfig extends string
        ? ReadonlyAccount<TAccountRestakingConfig>
        : TAccountRestakingConfig,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountOperator extends string
        ? ReadonlyAccount<TAccountOperator>
        : TAccountOperator,
      TAccountBallotBox extends string
        ? ReadonlyAccount<TAccountBallotBox>
        : TAccountBallotBox,
      TAccountOperatorEpochRewardRouter extends string
        ? ReadonlyAccount<TAccountOperatorEpochRewardRouter>
        : TAccountOperatorEpochRewardRouter,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            IAccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountRestakingProgramId extends string
        ? ReadonlyAccount<TAccountRestakingProgramId>
        : TAccountRestakingProgramId,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeOperatorEpochRewardRouterInstructionData = {
  discriminator: number;
  firstSlotOfNcnEpoch: Option<bigint>;
};

export type InitializeOperatorEpochRewardRouterInstructionDataArgs = {
  firstSlotOfNcnEpoch: OptionOrNullable<number | bigint>;
};

export function getInitializeOperatorEpochRewardRouterInstructionDataEncoder(): Encoder<InitializeOperatorEpochRewardRouterInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['firstSlotOfNcnEpoch', getOptionEncoder(getU64Encoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_OPERATOR_EPOCH_REWARD_ROUTER_DISCRIMINATOR,
    })
  );
}

export function getInitializeOperatorEpochRewardRouterInstructionDataDecoder(): Decoder<InitializeOperatorEpochRewardRouterInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['firstSlotOfNcnEpoch', getOptionDecoder(getU64Decoder())],
  ]);
}

export function getInitializeOperatorEpochRewardRouterInstructionDataCodec(): Codec<
  InitializeOperatorEpochRewardRouterInstructionDataArgs,
  InitializeOperatorEpochRewardRouterInstructionData
> {
  return combineCodec(
    getInitializeOperatorEpochRewardRouterInstructionDataEncoder(),
    getInitializeOperatorEpochRewardRouterInstructionDataDecoder()
  );
}

export type InitializeOperatorEpochRewardRouterInput<
  TAccountRestakingConfig extends string = string,
  TAccountNcn extends string = string,
  TAccountOperator extends string = string,
  TAccountBallotBox extends string = string,
  TAccountOperatorEpochRewardRouter extends string = string,
  TAccountPayer extends string = string,
  TAccountRestakingProgramId extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  restakingConfig: Address<TAccountRestakingConfig>;
  ncn: Address<TAccountNcn>;
  operator: Address<TAccountOperator>;
  ballotBox: Address<TAccountBallotBox>;
  operatorEpochRewardRouter: Address<TAccountOperatorEpochRewardRouter>;
  payer: TransactionSigner<TAccountPayer>;
  restakingProgramId: Address<TAccountRestakingProgramId>;
  systemProgram?: Address<TAccountSystemProgram>;
  firstSlotOfNcnEpoch: InitializeOperatorEpochRewardRouterInstructionDataArgs['firstSlotOfNcnEpoch'];
};

export function getInitializeOperatorEpochRewardRouterInstruction<
  TAccountRestakingConfig extends string,
  TAccountNcn extends string,
  TAccountOperator extends string,
  TAccountBallotBox extends string,
  TAccountOperatorEpochRewardRouter extends string,
  TAccountPayer extends string,
  TAccountRestakingProgramId extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: InitializeOperatorEpochRewardRouterInput<
    TAccountRestakingConfig,
    TAccountNcn,
    TAccountOperator,
    TAccountBallotBox,
    TAccountOperatorEpochRewardRouter,
    TAccountPayer,
    TAccountRestakingProgramId,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeOperatorEpochRewardRouterInstruction<
  TProgramAddress,
  TAccountRestakingConfig,
  TAccountNcn,
  TAccountOperator,
  TAccountBallotBox,
  TAccountOperatorEpochRewardRouter,
  TAccountPayer,
  TAccountRestakingProgramId,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    restakingConfig: {
      value: input.restakingConfig ?? null,
      isWritable: false,
    },
    ncn: { value: input.ncn ?? null, isWritable: false },
    operator: { value: input.operator ?? null, isWritable: false },
    ballotBox: { value: input.ballotBox ?? null, isWritable: false },
    operatorEpochRewardRouter: {
      value: input.operatorEpochRewardRouter ?? null,
      isWritable: false,
    },
    payer: { value: input.payer ?? null, isWritable: true },
    restakingProgramId: {
      value: input.restakingProgramId ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.restakingConfig),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.operator),
      getAccountMeta(accounts.ballotBox),
      getAccountMeta(accounts.operatorEpochRewardRouter),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.restakingProgramId),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getInitializeOperatorEpochRewardRouterInstructionDataEncoder().encode(
      args as InitializeOperatorEpochRewardRouterInstructionDataArgs
    ),
  } as InitializeOperatorEpochRewardRouterInstruction<
    TProgramAddress,
    TAccountRestakingConfig,
    TAccountNcn,
    TAccountOperator,
    TAccountBallotBox,
    TAccountOperatorEpochRewardRouter,
    TAccountPayer,
    TAccountRestakingProgramId,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedInitializeOperatorEpochRewardRouterInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    restakingConfig: TAccountMetas[0];
    ncn: TAccountMetas[1];
    operator: TAccountMetas[2];
    ballotBox: TAccountMetas[3];
    operatorEpochRewardRouter: TAccountMetas[4];
    payer: TAccountMetas[5];
    restakingProgramId: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
  };
  data: InitializeOperatorEpochRewardRouterInstructionData;
};

export function parseInitializeOperatorEpochRewardRouterInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedInitializeOperatorEpochRewardRouterInstruction<
  TProgram,
  TAccountMetas
> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      restakingConfig: getNextAccount(),
      ncn: getNextAccount(),
      operator: getNextAccount(),
      ballotBox: getNextAccount(),
      operatorEpochRewardRouter: getNextAccount(),
      payer: getNextAccount(),
      restakingProgramId: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeOperatorEpochRewardRouterInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
