/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const PROCESS_OPERATOR_EPOCH_REWARD_POOL_DISCRIMINATOR = 14;

export function getProcessOperatorEpochRewardPoolDiscriminatorBytes() {
  return getU8Encoder().encode(
    PROCESS_OPERATOR_EPOCH_REWARD_POOL_DISCRIMINATOR
  );
}

export type ProcessOperatorEpochRewardPoolInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountRestakingConfig extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountOperator extends string | IAccountMeta<string> = string,
  TAccountOperatorSnapshot extends string | IAccountMeta<string> = string,
  TAccountOperatorRewardRouter extends string | IAccountMeta<string> = string,
  TAccountRestakingProgramId extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountRestakingConfig extends string
        ? ReadonlyAccount<TAccountRestakingConfig>
        : TAccountRestakingConfig,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountOperator extends string
        ? ReadonlyAccount<TAccountOperator>
        : TAccountOperator,
      TAccountOperatorSnapshot extends string
        ? ReadonlyAccount<TAccountOperatorSnapshot>
        : TAccountOperatorSnapshot,
      TAccountOperatorRewardRouter extends string
        ? ReadonlyAccount<TAccountOperatorRewardRouter>
        : TAccountOperatorRewardRouter,
      TAccountRestakingProgramId extends string
        ? ReadonlyAccount<TAccountRestakingProgramId>
        : TAccountRestakingProgramId,
      ...TRemainingAccounts,
    ]
  >;

export type ProcessOperatorEpochRewardPoolInstructionData = {
  discriminator: number;
  firstSlotOfNcnEpoch: Option<bigint>;
};

export type ProcessOperatorEpochRewardPoolInstructionDataArgs = {
  firstSlotOfNcnEpoch: OptionOrNullable<number | bigint>;
};

export function getProcessOperatorEpochRewardPoolInstructionDataEncoder(): Encoder<ProcessOperatorEpochRewardPoolInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['firstSlotOfNcnEpoch', getOptionEncoder(getU64Encoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: PROCESS_OPERATOR_EPOCH_REWARD_POOL_DISCRIMINATOR,
    })
  );
}

export function getProcessOperatorEpochRewardPoolInstructionDataDecoder(): Decoder<ProcessOperatorEpochRewardPoolInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['firstSlotOfNcnEpoch', getOptionDecoder(getU64Decoder())],
  ]);
}

export function getProcessOperatorEpochRewardPoolInstructionDataCodec(): Codec<
  ProcessOperatorEpochRewardPoolInstructionDataArgs,
  ProcessOperatorEpochRewardPoolInstructionData
> {
  return combineCodec(
    getProcessOperatorEpochRewardPoolInstructionDataEncoder(),
    getProcessOperatorEpochRewardPoolInstructionDataDecoder()
  );
}

export type ProcessOperatorEpochRewardPoolInput<
  TAccountRestakingConfig extends string = string,
  TAccountNcn extends string = string,
  TAccountOperator extends string = string,
  TAccountOperatorSnapshot extends string = string,
  TAccountOperatorRewardRouter extends string = string,
  TAccountRestakingProgramId extends string = string,
> = {
  restakingConfig: Address<TAccountRestakingConfig>;
  ncn: Address<TAccountNcn>;
  operator: Address<TAccountOperator>;
  operatorSnapshot: Address<TAccountOperatorSnapshot>;
  operatorRewardRouter: Address<TAccountOperatorRewardRouter>;
  restakingProgramId: Address<TAccountRestakingProgramId>;
  firstSlotOfNcnEpoch: ProcessOperatorEpochRewardPoolInstructionDataArgs['firstSlotOfNcnEpoch'];
};

export function getProcessOperatorEpochRewardPoolInstruction<
  TAccountRestakingConfig extends string,
  TAccountNcn extends string,
  TAccountOperator extends string,
  TAccountOperatorSnapshot extends string,
  TAccountOperatorRewardRouter extends string,
  TAccountRestakingProgramId extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: ProcessOperatorEpochRewardPoolInput<
    TAccountRestakingConfig,
    TAccountNcn,
    TAccountOperator,
    TAccountOperatorSnapshot,
    TAccountOperatorRewardRouter,
    TAccountRestakingProgramId
  >,
  config?: { programAddress?: TProgramAddress }
): ProcessOperatorEpochRewardPoolInstruction<
  TProgramAddress,
  TAccountRestakingConfig,
  TAccountNcn,
  TAccountOperator,
  TAccountOperatorSnapshot,
  TAccountOperatorRewardRouter,
  TAccountRestakingProgramId
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    restakingConfig: {
      value: input.restakingConfig ?? null,
      isWritable: false,
    },
    ncn: { value: input.ncn ?? null, isWritable: false },
    operator: { value: input.operator ?? null, isWritable: false },
    operatorSnapshot: {
      value: input.operatorSnapshot ?? null,
      isWritable: false,
    },
    operatorRewardRouter: {
      value: input.operatorRewardRouter ?? null,
      isWritable: false,
    },
    restakingProgramId: {
      value: input.restakingProgramId ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.restakingConfig),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.operator),
      getAccountMeta(accounts.operatorSnapshot),
      getAccountMeta(accounts.operatorRewardRouter),
      getAccountMeta(accounts.restakingProgramId),
    ],
    programAddress,
    data: getProcessOperatorEpochRewardPoolInstructionDataEncoder().encode(
      args as ProcessOperatorEpochRewardPoolInstructionDataArgs
    ),
  } as ProcessOperatorEpochRewardPoolInstruction<
    TProgramAddress,
    TAccountRestakingConfig,
    TAccountNcn,
    TAccountOperator,
    TAccountOperatorSnapshot,
    TAccountOperatorRewardRouter,
    TAccountRestakingProgramId
  >;

  return instruction;
}

export type ParsedProcessOperatorEpochRewardPoolInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    restakingConfig: TAccountMetas[0];
    ncn: TAccountMetas[1];
    operator: TAccountMetas[2];
    operatorSnapshot: TAccountMetas[3];
    operatorRewardRouter: TAccountMetas[4];
    restakingProgramId: TAccountMetas[5];
  };
  data: ProcessOperatorEpochRewardPoolInstructionData;
};

export function parseProcessOperatorEpochRewardPoolInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedProcessOperatorEpochRewardPoolInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      restakingConfig: getNextAccount(),
      ncn: getNextAccount(),
      operator: getNextAccount(),
      operatorSnapshot: getNextAccount(),
      operatorRewardRouter: getNextAccount(),
      restakingProgramId: getNextAccount(),
    },
    data: getProcessOperatorEpochRewardPoolInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
