/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const REGISTER_VAULT_DISCRIMINATOR = 3;

export function getRegisterVaultDiscriminatorBytes() {
  return getU8Encoder().encode(REGISTER_VAULT_DISCRIMINATOR);
}

export type RegisterVaultInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountVaultRegistry extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountVault extends string | IAccountMeta<string> = string,
  TAccountNcnVaultTicket extends string | IAccountMeta<string> = string,
  TAccountRestakingProgramId extends string | IAccountMeta<string> = string,
  TAccountVaultProgramId extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountVaultRegistry extends string
        ? WritableAccount<TAccountVaultRegistry>
        : TAccountVaultRegistry,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountVault extends string
        ? ReadonlyAccount<TAccountVault>
        : TAccountVault,
      TAccountNcnVaultTicket extends string
        ? ReadonlyAccount<TAccountNcnVaultTicket>
        : TAccountNcnVaultTicket,
      TAccountRestakingProgramId extends string
        ? ReadonlyAccount<TAccountRestakingProgramId>
        : TAccountRestakingProgramId,
      TAccountVaultProgramId extends string
        ? ReadonlyAccount<TAccountVaultProgramId>
        : TAccountVaultProgramId,
      ...TRemainingAccounts,
    ]
  >;

export type RegisterVaultInstructionData = { discriminator: number };

export type RegisterVaultInstructionDataArgs = {};

export function getRegisterVaultInstructionDataEncoder(): Encoder<RegisterVaultInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: REGISTER_VAULT_DISCRIMINATOR })
  );
}

export function getRegisterVaultInstructionDataDecoder(): Decoder<RegisterVaultInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getRegisterVaultInstructionDataCodec(): Codec<
  RegisterVaultInstructionDataArgs,
  RegisterVaultInstructionData
> {
  return combineCodec(
    getRegisterVaultInstructionDataEncoder(),
    getRegisterVaultInstructionDataDecoder()
  );
}

export type RegisterVaultInput<
  TAccountVaultRegistry extends string = string,
  TAccountNcn extends string = string,
  TAccountVault extends string = string,
  TAccountNcnVaultTicket extends string = string,
  TAccountRestakingProgramId extends string = string,
  TAccountVaultProgramId extends string = string,
> = {
  vaultRegistry: Address<TAccountVaultRegistry>;
  ncn: Address<TAccountNcn>;
  vault: Address<TAccountVault>;
  ncnVaultTicket: Address<TAccountNcnVaultTicket>;
  restakingProgramId: Address<TAccountRestakingProgramId>;
  vaultProgramId: Address<TAccountVaultProgramId>;
};

export function getRegisterVaultInstruction<
  TAccountVaultRegistry extends string,
  TAccountNcn extends string,
  TAccountVault extends string,
  TAccountNcnVaultTicket extends string,
  TAccountRestakingProgramId extends string,
  TAccountVaultProgramId extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: RegisterVaultInput<
    TAccountVaultRegistry,
    TAccountNcn,
    TAccountVault,
    TAccountNcnVaultTicket,
    TAccountRestakingProgramId,
    TAccountVaultProgramId
  >,
  config?: { programAddress?: TProgramAddress }
): RegisterVaultInstruction<
  TProgramAddress,
  TAccountVaultRegistry,
  TAccountNcn,
  TAccountVault,
  TAccountNcnVaultTicket,
  TAccountRestakingProgramId,
  TAccountVaultProgramId
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vaultRegistry: { value: input.vaultRegistry ?? null, isWritable: true },
    ncn: { value: input.ncn ?? null, isWritable: false },
    vault: { value: input.vault ?? null, isWritable: false },
    ncnVaultTicket: { value: input.ncnVaultTicket ?? null, isWritable: false },
    restakingProgramId: {
      value: input.restakingProgramId ?? null,
      isWritable: false,
    },
    vaultProgramId: { value: input.vaultProgramId ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.vaultRegistry),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.ncnVaultTicket),
      getAccountMeta(accounts.restakingProgramId),
      getAccountMeta(accounts.vaultProgramId),
    ],
    programAddress,
    data: getRegisterVaultInstructionDataEncoder().encode({}),
  } as RegisterVaultInstruction<
    TProgramAddress,
    TAccountVaultRegistry,
    TAccountNcn,
    TAccountVault,
    TAccountNcnVaultTicket,
    TAccountRestakingProgramId,
    TAccountVaultProgramId
  >;

  return instruction;
}

export type ParsedRegisterVaultInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vaultRegistry: TAccountMetas[0];
    ncn: TAccountMetas[1];
    vault: TAccountMetas[2];
    ncnVaultTicket: TAccountMetas[3];
    restakingProgramId: TAccountMetas[4];
    vaultProgramId: TAccountMetas[5];
  };
  data: RegisterVaultInstructionData;
};

export function parseRegisterVaultInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedRegisterVaultInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vaultRegistry: getNextAccount(),
      ncn: getNextAccount(),
      vault: getNextAccount(),
      ncnVaultTicket: getNextAccount(),
      restakingProgramId: getNextAccount(),
      vaultProgramId: getNextAccount(),
    },
    data: getRegisterVaultInstructionDataDecoder().decode(instruction.data),
  };
}
