[package]
name = "stake-meta-generator"
version = "0.0.1"
edition = { workspace = true }
description = "Generate stake-meta artifacts from Solana snapshots"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }

[[bin]]
name = "stake-meta-generator"
path = "src/main.rs"

[dependencies]
agave-snapshots = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
clap = { workspace = true }
itertools = "0.11"
jito-priority-fee-distribution-sdk = { workspace = true }
jito-stake-meta-types = { workspace = true }
jito-tip-distribution-sdk = { workspace = true }
jito-tip-payment-sdk = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
solana-accounts-db = { workspace = true }
solana-genesis-utils = { workspace = true, features = ["agave-unstable-api"] }
solana-runtime = { workspace = true }
solana-sdk = { workspace = true }
solana-stake-interface = { workspace = true }
solana-vote = { workspace = true }
thiserror = { workspace = true }
