/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from '@solana/web3.js';
import {
  getRewardRoutesDecoder,
  getRewardRoutesEncoder,
  type RewardRoutes,
  type RewardRoutesArgs,
} from '../types';

export type OperatorEpochRewardRouter = {
  discriminator: bigint;
  operator: Address;
  ncn: Address;
  ncnEpoch: bigint;
  bump: number;
  slotCreated: bigint;
  rewardPool: bigint;
  operatorRewards: bigint;
  reserved: Array<number>;
  vaultRewards: Array<RewardRoutes>;
};

export type OperatorEpochRewardRouterArgs = {
  discriminator: number | bigint;
  operator: Address;
  ncn: Address;
  ncnEpoch: number | bigint;
  bump: number;
  slotCreated: number | bigint;
  rewardPool: number | bigint;
  operatorRewards: number | bigint;
  reserved: Array<number>;
  vaultRewards: Array<RewardRoutesArgs>;
};

export function getOperatorEpochRewardRouterEncoder(): Encoder<OperatorEpochRewardRouterArgs> {
  return getStructEncoder([
    ['discriminator', getU64Encoder()],
    ['operator', getAddressEncoder()],
    ['ncn', getAddressEncoder()],
    ['ncnEpoch', getU64Encoder()],
    ['bump', getU8Encoder()],
    ['slotCreated', getU64Encoder()],
    ['rewardPool', getU64Encoder()],
    ['operatorRewards', getU64Encoder()],
    ['reserved', getArrayEncoder(getU8Encoder(), { size: 128 })],
    ['vaultRewards', getArrayEncoder(getRewardRoutesEncoder(), { size: 32 })],
  ]);
}

export function getOperatorEpochRewardRouterDecoder(): Decoder<OperatorEpochRewardRouter> {
  return getStructDecoder([
    ['discriminator', getU64Decoder()],
    ['operator', getAddressDecoder()],
    ['ncn', getAddressDecoder()],
    ['ncnEpoch', getU64Decoder()],
    ['bump', getU8Decoder()],
    ['slotCreated', getU64Decoder()],
    ['rewardPool', getU64Decoder()],
    ['operatorRewards', getU64Decoder()],
    ['reserved', getArrayDecoder(getU8Decoder(), { size: 128 })],
    ['vaultRewards', getArrayDecoder(getRewardRoutesDecoder(), { size: 32 })],
  ]);
}

export function getOperatorEpochRewardRouterCodec(): Codec<
  OperatorEpochRewardRouterArgs,
  OperatorEpochRewardRouter
> {
  return combineCodec(
    getOperatorEpochRewardRouterEncoder(),
    getOperatorEpochRewardRouterDecoder()
  );
}

export function decodeOperatorEpochRewardRouter<
  TAddress extends string = string,
>(
  encodedAccount: EncodedAccount<TAddress>
): Account<OperatorEpochRewardRouter, TAddress>;
export function decodeOperatorEpochRewardRouter<
  TAddress extends string = string,
>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<OperatorEpochRewardRouter, TAddress>;
export function decodeOperatorEpochRewardRouter<
  TAddress extends string = string,
>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
):
  | Account<OperatorEpochRewardRouter, TAddress>
  | MaybeAccount<OperatorEpochRewardRouter, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getOperatorEpochRewardRouterDecoder()
  );
}

export async function fetchOperatorEpochRewardRouter<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<OperatorEpochRewardRouter, TAddress>> {
  const maybeAccount = await fetchMaybeOperatorEpochRewardRouter(
    rpc,
    address,
    config
  );
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeOperatorEpochRewardRouter<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<OperatorEpochRewardRouter, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeOperatorEpochRewardRouter(maybeAccount);
}

export async function fetchAllOperatorEpochRewardRouter(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<OperatorEpochRewardRouter>[]> {
  const maybeAccounts = await fetchAllMaybeOperatorEpochRewardRouter(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeOperatorEpochRewardRouter(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<OperatorEpochRewardRouter>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeOperatorEpochRewardRouter(maybeAccount)
  );
}
